# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sei_pb2 as sei__pb2


class IdenServiceStub(object):
    """识别服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/sei.IdenService/Identify',
                request_serializer=sei__pb2.IdenReq.SerializeToString,
                response_deserializer=sei__pb2.IdenRes.FromString,
                )


class IdenServiceServicer(object):
    """识别服务
    """

    def Identify(self, request, context):
        """个体识别
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=sei__pb2.IdenReq.FromString,
                    response_serializer=sei__pb2.IdenRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sei.IdenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdenService(object):
    """识别服务
    """

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sei.IdenService/Identify',
            sei__pb2.IdenReq.SerializeToString,
            sei__pb2.IdenRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
