# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sei.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsei.proto\x12\x03sei\"q\n\tIdenParam\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x01\x12\x12\n\nband_width\x18\x03 \x01(\x01\x12\x13\n\x0bsymbol_rate\x18\x04 \x01(\x01\x12\x13\n\x0b\x63\x65nter_freq\x18\x05 \x01(\x01\x12\x11\n\tfile_path\x18\x06 \x01(\t\";\n\nIdenResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\")\n\x07IdenReq\x12\x1e\n\x06params\x18\x01 \x03(\x0b\x32\x0e.sei.IdenParam\"+\n\x07IdenRes\x12 \n\x07results\x18\x01 \x03(\x0b\x32\x0f.sei.IdenResult25\n\x0bIdenService\x12&\n\x08Identify\x12\x0c.sei.IdenReq\x1a\x0c.sei.IdenResB\x0c\xaa\x02\tSEI.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sei_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\tSEI.Proto'
  _globals['_IDENPARAM']._serialized_start=18
  _globals['_IDENPARAM']._serialized_end=131
  _globals['_IDENRESULT']._serialized_start=133
  _globals['_IDENRESULT']._serialized_end=192
  _globals['_IDENREQ']._serialized_start=194
  _globals['_IDENREQ']._serialized_end=235
  _globals['_IDENRES']._serialized_start=237
  _globals['_IDENRES']._serialized_end=280
  _globals['_IDENSERVICE']._serialized_start=282
  _globals['_IDENSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
